// Seeded suggestions for the wizard tag inputs. Members can also enter free text.
export const HELP_TAG_SUGGESTIONS = [
  'B2B marketing',
  'B2C marketing',
  'SEO',
  'Content strategy',
  'Product strategy',
  'Fundraising',
  'Pitch deck review',
  'Hiring first engineers',
  'Sales',
  'Partnerships',
  'Legal (employment)',
  'Legal (contracts)',
  'Tax / accounting',
  'Barcelona visas / autónomo',
  'Office / coworking recs',
  'PR / press',
  'Design / branding',
  'Web development',
  'Mobile development',
  'Data / analytics',
  'Customer support setup',
  'Operations',
  'Investor intros',
  'Mentorship',
] as const;
